"""
Service for ingesting text into UserKnowledge chunks.
"""

from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.knowledge_repository import KnowledgeRepository


class KnowledgeService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = KnowledgeRepository(db)

    async def ingest_knowledge(self, user_id: str, content: str, source_type: str) -> None:
        """Add text as UserKnowledge chunk - embedding is generated in background."""
        if not content or not content.strip():
            return
        
        from app.models.user_knowledge import UserKnowledge
        import uuid
        
        chunk = UserKnowledge(
            id=str(uuid.uuid4()),
            user_id=user_id,
            content=content,
            embedding=None,  # Will be generated by background task
            source_type=source_type,
            embedding_status="pending"
        )
        self.db.add(chunk)
        await self.db.flush()
        
        from app.tasks.knowledge_embedding_task import generate_knowledge_embedding
        generate_knowledge_embedding.delay(chunk.id)

    async def replace_user_knowledge(
        self, user_id: str, chunks: list[str], source_type: str
    ) -> None:
        """Clear old knowledge for a source and add new chunks."""
        await self.repo.clear_user_knowledge(user_id, source_type=source_type)
        
        from app.models.user_knowledge import UserKnowledge
        import uuid
        
        for content in chunks:
            if content and content.strip():
                chunk = UserKnowledge(
                    id=str(uuid.uuid4()),
                    user_id=user_id,
                    content=content,
                    embedding=None,  # Will be generated by background task
                    source_type=source_type,
                    embedding_status="pending"
                )
                self.db.add(chunk)
        
        await self.db.flush()
        
        from app.tasks.knowledge_embedding_task import batch_generate_knowledge_embeddings
        batch_generate_knowledge_embeddings.delay(user_id, source_type)
