from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.user import User
from app.schemas.resume import ResumeOut, ResumeGenerateRequest, ResumeUpdateRequest
from app.api.deps import get_current_user
from app.services.resume_service import ResumeService
from app.repositories.resume_repository import ResumeRepository

router = APIRouter(prefix="/api/resume", tags=["resume"])


def _resume_to_out(r, warnings: list[str] = []) -> ResumeOut:
    """Convert a Resume ORM object to ResumeOut schema."""
    return ResumeOut(
        id=r.id,
        user_id=r.user_id,
        target_role=r.target_role,
        professional_summary=r.professional_summary,
        skills=r.skills,
        experience=r.experience or [],
        education=r.education or [],
        projects=r.projects or [],
        certifications=r.certifications or [],
        trending_skills_highlighted=r.trending_skills_highlighted or [],
        created_at=r.created_at,
        updated_at=getattr(r, "updated_at", None),
        warnings=warnings,
    )


@router.post("/generate", response_model=ResumeOut)
async def create_resume(
    req: ResumeGenerateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate an ATS-optimized resume for the authenticated user.

    The resume is built from:
    - User's profile (name, skills, career interest)
    - Work experiences stored on the profile
    - Academic transcript knowledge (education section)
    - CV / GitHub knowledge (projects section)
    - Real market in-demand skills for the target role

    Returns the resume with a `warnings` list for any missing sections.
    Raises 422 for user-facing issues. Raises 500 for unexpected errors.
    """
    try:
        service = ResumeService(db, current_user.id)
        result = await service.generate_and_save(target_role=req.target_role)
        return ResumeOut(**{k: v for k, v in result.items()})
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception:
        raise HTTPException(
            status_code=500,
            detail="An unexpected error occurred while generating the resume. Please try again.",
        )


@router.get("", response_model=list[ResumeOut])
async def list_resumes(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List all resumes generated by the current user, newest first."""
    repo = ResumeRepository(db)
    resumes = await repo.list_by_user(current_user.id)
    return [_resume_to_out(r) for r in resumes]


@router.get("/{resume_id}", response_model=ResumeOut)
async def get_resume(
    resume_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get a specific resume by ID."""
    repo = ResumeRepository(db)
    resume = await repo.get_by_id(resume_id, current_user.id)
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found")
    return _resume_to_out(resume)


@router.patch("/{resume_id}", response_model=ResumeOut)
async def update_resume(
    resume_id: str,
    req: ResumeUpdateRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Partially update a generated resume.

    All fields are optional — only the fields you provide will be updated.
    This lets the frontend implement section-by-section editing:
    - Edit the professional summary
    - Add/remove experience entries
    - Update skills
    - Add certifications
    - etc.

    The `updated_at` timestamp is automatically set on every update.
    Returns 404 if the resume doesn't exist or doesn't belong to the user.
    """
    try:
        service = ResumeService(db, current_user.id)

        # Convert request to dict, excluding unset fields and None values
        # so only explicitly provided fields are updated
        update_data = req.model_dump(exclude_unset=True, exclude_none=True)

        # Serialize nested Pydantic models to plain dicts for JSON storage
        for key in ("skills", "experience", "education", "projects", "certifications"):
            if key in update_data and update_data[key] is not None:
                val = update_data[key]
                if isinstance(val, list):
                    update_data[key] = [
                        item.model_dump() if hasattr(item, "model_dump") else item
                        for item in val
                    ]
                elif hasattr(val, "model_dump"):
                    update_data[key] = val.model_dump()

        result = await service.update_resume(resume_id, update_data)
        return ResumeOut(**{k: v for k, v in result.items()})
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception:
        raise HTTPException(
            status_code=500,
            detail="An unexpected error occurred while updating the resume.",
        )


@router.delete("/{resume_id}", status_code=204)
async def delete_resume(
    resume_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Delete a resume permanently.
    Returns 404 if the resume doesn't exist or doesn't belong to the user.
    """
    try:
        service = ResumeService(db, current_user.id)
        await service.delete_resume(resume_id)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
