"""Add academic transcript models

Revision ID: ab88e4f174fb
Revises: ad65d55cc035
Create Date: 2026-04-06 16:23:17.341376+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab88e4f174fb"
down_revision: Union[str, None] = "ad65d55cc035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: academic_transcripts table is already created in migration g0b4c7d96e83
    # So we skip creating it here to avoid duplicate table errors

    # NOTE: transcript_configs table is already created in migration f9a3b6c95d72
    # So we skip creating it here as well

    # op.create_table('academic_transcripts',
    # ...
    # )
    # op.create_index(...)

    # op.create_table(
    #     "transcript_configs",
    #     ...
    # )
    # op.create_index(...)

    op.drop_index("ix_oauth_accounts_provider", table_name="oauth_accounts")
    op.drop_index("ix_oauth_accounts_user_id", table_name="oauth_accounts")
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_users_oauth_provider_id", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_users_oauth_provider_id",
        "users",
        ["oauth_provider", "oauth_id"],
        unique=False,
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.create_index(
        "ix_oauth_accounts_user_id", "oauth_accounts", ["user_id"], unique=False
    )
    op.create_index(
        "ix_oauth_accounts_provider", "oauth_accounts", ["provider"], unique=False
    )
    # NOTE: transcript_configs table is dropped in migration f9a3b6c95d72 downgrade
    # So we don't drop it here
    # op.drop_index(
    #     op.f("ix_transcript_configs_user_id"), table_name="transcript_configs"
    # )
    # op.drop_table("transcript_configs")

    # NOTE: academic_transcripts table is dropped in migration g0b4c7d96e83 downgrade
    # So we don't drop it here
    # ### end Alembic commands ###
