"""Add academic transcript models

Revision ID: ab88e4f174fb
Revises: ad65d55cc035
Create Date: 2026-04-06 16:23:17.341376+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab88e4f174fb'
down_revision: Union[str, None] = 'ad65d55cc035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('transcript_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_user_version')
    )
    op.create_index(op.f('ix_academic_transcripts_student_id'), 'academic_transcripts', ['student_id'], unique=False)
    op.create_index(op.f('ix_academic_transcripts_user_id'), 'academic_transcripts', ['user_id'], unique=False)
    op.create_index('ix_academic_transcripts_user_version', 'academic_transcripts', ['user_id', 'version'], unique=False)
    op.create_table('transcript_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gpa_scale', sa.Float(), nullable=False),
    sa.Column('grading_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grade_display_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_configs_user_id'), 'transcript_configs', ['user_id'], unique=True)
    op.drop_index('ix_oauth_accounts_provider', table_name='oauth_accounts')
    op.drop_index('ix_oauth_accounts_user_id', table_name='oauth_accounts')
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_oauth_provider_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_oauth_provider_id', 'users', ['oauth_provider', 'oauth_id'], unique=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('ix_oauth_accounts_provider', 'oauth_accounts', ['provider'], unique=False)
    op.drop_index(op.f('ix_transcript_configs_user_id'), table_name='transcript_configs')
    op.drop_table('transcript_configs')
    op.drop_index('ix_academic_transcripts_user_version', table_name='academic_transcripts')
    op.drop_index(op.f('ix_academic_transcripts_user_id'), table_name='academic_transcripts')
    op.drop_index(op.f('ix_academic_transcripts_student_id'), table_name='academic_transcripts')
    op.drop_table('academic_transcripts')
    # ### end Alembic commands ###
